version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --clean

  dependencyUpdates:
    desc: Show dependency updates
    aliases: [ outdated ]
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct

  mingo:
    cmds:
      - mingo -tests -v

  test:
    deps: [ build ]
    cmds:
      #- dist/tdms-cli_linux_amd64_v1/tdms-cli test ~/NI/data4.tdms
      - dist/tdms-cli_linux_amd64_v1/tdms-cli test ~/NI/test2.tdms

  test2:
    deps: [ build ]
    cmds:
      #- dist/tdms-cli_linux_amd64_v1/tdms-cli test ~/NI/data4.tdms
      - dist/tdms-cli_linux_amd64_v1/tdms-cli test ~/Concretecho/rawdata/2025-12-10_15.29.16/acoustics/2025-12-10_15.30.37_T002_acoustic.tdms

  test3:
    deps: [ build ]
    cmds:
      - dist/tdms-cli_linux_amd64_v1/tdms-cli convert ~/Concretecho/rawdata/2025-12-10_15.29.16/acoustics/2025-12-10_15.30.37_T002_acoustic.tdms output/output.nc
